# Site settings
title: "Neels van Wyk Resume"
description: "My simple online CV"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Neels v. Wyk"
resume_title:                   "Kubernetes Enthusiast, Linux Specialist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "employ@neels.tech"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+27 83 385 9887"
resume_contact_address:         "14 Collins St, Windsor Glen, Johannsburg"

resume_header_contact_info:     "14 Collins St, Windsor Glen, Johannsburg • +27 83 385 0887 • employ@neels.tech"
display_header_contact_info:    "false"

resume_header_intro: "<p>I like to play with new technologies. I have a passion for all things k8s. I like to automate, and I'm driven by the constant need to improve. Learning by doing is fun, and teaching be example is how it's meant to be.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
#resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Neels-v-Wyk"
  #  resume_twitter_url:           "http://twitter.com/jglovier"
  #  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://neels.tech"
  #  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
